### ISSUE TITLE
[Desktop] Crash upon replacing v3.3.0 with v3.4.0

### ISSUE THREAD

**Issue by matthewmorek** [voltraco/beta#76]
#### Issue
```
TypeError: Cannot read property 'includes' of undefined
    at n (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:7:19280)
    at Object.<anonymous> (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:7:19760)
    at t (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:270)
    at Object.<anonymous> (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:7:7559)
    at t (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:270)
    at Object.<anonymous> (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:350577)
    at t (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:270)
    at /Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:630
    at Object.<anonymous> (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:1:641)
    at Object.<anonymous> (/Applications/Voltra.app/Contents/Resources/app.asar/src/bundle.js:8:3)
```

#### Impact
This error prevents Voltra from starting up correctly and gets stuck in a crash loop. The only way to escape is to quit or force quit the application from menubar.

#### Steps to reproduce
1. Install Voltra Desktop `v3.3.0`.
2. Add some music and set up sync.
3. Quit and replace with `v3.4.0`.
4. Open Voltra.

#### Details
```
Voltra for Desktop (Mac) v3.3.0
macOS 10.12.6 (16G1036)
```

**Comment by heapwolf** [comment]
This is a special case, specifically for you. You have a `developer` account and we got rid of most of the code that supported this. We will get your account set up properly to handle the new release :)
